### ISSUE TITLE
Regulated voltage level?

### ISSUE THREAD

**Issue by neopostmodern** [PhiBabin/Redox-Lipo-Adapter#3]
I come here from [this issue](https://github.com/mattdibi/redox-keyboard/issues/156#issuecomment-1783868794) and am interested in integrating this into my Redox. While looking through the repo I got confused about the regulated voltage of the most recent design.
At the bottom of the README it says "Change regulated voltage from 3.3V to 3V", but [the schematic](https://github.com/PhiBabin/Redox-Lipo-Adapter/blob/main/schematic_v1.3.pdf) mentions a "3.3V regulator" with no further specification of `VREG`. So – which is it?

I'm asking because my current hypothesis to mitigate connectivity issues I'm facing is running the Redox at a [slightly elevated voltage](https://github.com/mattdibi/redox-keyboard/issues/55).

**Comment by PhiBabin** [comment]
V1.0 has a 3.3V regulator. V1.2 and V1.3 used a 3V regulator. In theory, you get better battery life with a 3V regulator, since you can use the 4.2V to 3.0V range of the battery. I don't know if it actually makes a significant difference in practice, since the Li-po's voltage is not linear with the state of charge. So if you worry about low voltage, using the 3.3V should be fine (this is the one I use). The microcontroler (nRF51822) used by the Redox support an input voltage between 1.8V and 3.6V.
